### ISSUE TITLE
Black Screen When starting Mirror

### ISSUE THREAD

**Issue by pb3975** [ronny3050/email-mirror#8]
For some reason I can't get this module to work. Instead of the "configure your config.js file" message I get a completely black screen. Here's my module:
`{
			module: 'email',
            position: 'bottom_left',
            header: 'Email',
            config:{
                user: 'myemail@gmail.com',
                password: 'maypassword',
                host: 'imap.gmail.com',
                port: 993,
                tls: true,
                authTimeout: 10000,
                numberOfEmails: 5,
                fade: true
			}
		},`

**Comment by OsmelTorres** [comment]
Hi pb3975, How is your email module Folder's name? It must be just **email** and no **email-mirror**. Maybe you forgot when you copied the git clone htt...............git **email**
Just an idea.

**Comment by pb3975** [comment]
Hi @osmelTorres. Thank you! It looks like that worked! But now I've got a constant "Loading..." under the module

**Comment by OsmelTorres** [comment]
Hi **pb3975**, I haven't had that problem, for me the module is doing its Job, is able to connect thru imap to my mail server and gets my emails perfectly. In your case  looks like there is something failing maybe on the module side, or on the mail server side. You must find what is wrong in order to fix it.
I suggest a few thinks:

_1- Double check some of your config options like:_

  **user:** 'right@emailaddress',
  **password:** 'rightPassword',
  **host:** 'imap.gmail.com', (the right host for imap server)
  **port:** 993, (the right port for imap server)
      
_2- Debug a little bit_, I don't know how do you start your **_MagicMirror_**, so there are so many ways to debug. After make sure that **_MagicMirror_** is totally stopped, one way that I use is to connect from another machine thru ssh and then i do:
export DISPLAY=:0.0 
Then I run the MagicMirror manually  by using the following command from ~/MagicMirror Directory:
 npm start 
. so you can see on the terminal important output from your modules.

From this point you will probably see some Error messages than we can use to solve the problem.
I hope you can take some ideas from this tips.
Remember, don't give up.

**Comment by pb3975** [comment]
Thank you for your help and advice. I've made some progress, It seems my email inbox may be too large and is taking a while to load. When trying with an alternate account I was able to get it working.

**Comment by OsmelTorres** [comment]
Hi **pb3975**, I'm glad you have made some progress. If you got good results using an alternate email account then there is something related with the first email account that you were trying before.
 
About the long delay that you get, By default, the module only search for the **UNSEEN** (unread) messages, so that limit in some way the amount of messages to deal with. So, or you have thousands of unread messages or the mail server is very slow or some other logic reason is happening. 
If is true that you really have thousands of unread messages a good idea will be to clean up your INBOX from time to time. Otherwise there is a way to limit even more the amount of emails to deal with from the module  side by setting for example a Date, for example. Only get **UNSEEN** emails from 1-1-2017 to now. 
Good Luck

**Comment by ronny3050** [comment]
@pb3975 I apologize for the inconvenience, however, I am not aware of any way to stop reading all unseen messages. I can make it so that it displays only the first N emails, however, it will still take a long time to load if you have a large number of emails.
